### ISSUE TITLE
Exception: Could not match layer with a known op type

### ISSUE THREAD

**Issue by baharsalehpour** [ARM-software/DeepFreeze#3]
Hello, 

I'm trying to run the gen_verilog.py script on the basic Tensorflow MNIST tutorial. I'm getting an Exception: Could not match layer with a known op type. 

I'm new to tensorflow so I'm wondering if I can get some guidance with setting up the example. I have attached my setup files as well as the original tensorflow example that I'm using. 

[deepfreeze.zip](https://github.com/ARM-software/DeepFreeze/files/4465693/deepfreeze.zip)

**Comment by patrickthomashansen** [comment]
That exception message indicates an error in parsing your network. Te parser uses the endpoints file to find boundaries between NN layers. Because your network has only one layer, it only has one endpoint. The file should contain something like:
`{
 "y" : [NAME OF Y TENSOR]
}`
Where the name of the tensor is the result of `y.name`. Also, you don't need to provide the names of input and output tensors in your bash script, but if you do, the appropriate names can be found the same way
